module.exports = {
    angle: [0, 359],
    blur: 0,
    doNotRemove: false,
    fan: false,
    floatingInSpace: false,
    geyser: false,
    count: [6, 10],
    color: "#B91319",
    imageSrc: undefined,
    opacity: [0.10, 0.75],
    rotate: true,
    scalar: [0.15, 0.45],
    transformOrigin: "center center",
    transitionDuration: 400,
    transitionFunction: "ease-out",
    translateX: [0, 0],
    translateY: [15, 45],
    xNoise: 0,
    yNoise: 0,
};