var B = require("boots-utils");

module.exports = HeartImage;

function HeartImage(container, style, options) {
    this.container = container;
    this.style = style;
    this.image = document.createElement("img");
    this.image.src = options.imageSrc; // icon should be default;
    // TODO - height and width
}

HeartImage.prototype.addStyle = function(style) {
    console.log("Current style", this.image.style.cssText);
    console.log("Adding style: ", style);
    this.image.style.cssText += style;
    console.log("Post style: ", this.image.style.cssText);

    return this;
};

HeartImage.prototype.addTransform = function(transform) {
    this.style.transform = 0;
    console.log("Current transform", this.image.style.transform);
    console.log("Adding transform: ", transform);
    this.image.style.transform += transform;
    this.image.style.webkitTransform += transform;

    // this.image.style.cssText += "transform:" + this.image.style.transform + " " + transform + ";";
    console.log("After transform added", this.image.style.transform);
    // this.image.style.webkitTransform += (" " + transform);
    console.log("Post transform: ", this.image.style.cssText);

    return this;
};

HeartImage.prototype.show = function(next) {
    this.image.style.cssText += this.style;
    this.container.appendChild(this.image);
    if (next) next();
    return this;
};

HeartImage.prototype.hide = function(next) {
    console.log("HeartImage#hide NYI");
    // if (next) next();
};

HeartImage.prototype.remove = function(next) {
    this.container.removeChild(this.image);
    if (next) next();
    return this;
};


// animator generated by options
// x and y are set on an event