var B = require("boots-utils");

module.exports = Image;

function Image(container, style, options) {
    this.container = container;
    this.style = style;
    this.image = document.createElement("img");
    this.image.src = options.imageSrc; // icon should be default;
    this.imageHeight = options.imageHeight;
    this.imageWidth = options.imageWidth;
    // TODO - height and width
}

Image.prototype.addStyle = function(style) {
    this.image.style.cssText += style;
    return this;
};

Image.prototype.addTransform = function(transform) {
    this.style.transform = 0;
    this.image.style.transform += " " + transform;
    this.image.style.webkitTransform += " " + transform;
    return this;
};

Image.prototype.show = function(next) {
    this.image.style.cssText += this.style;
    this.container.appendChild(this.image);
    if (next) next();
    return this;
};

Image.prototype.hide = function(next) {
    console.log("Image#hide NYI");
    // if (next) next();
};

Image.prototype.remove = function(next) {
    this.container.removeChild(this.image);
    if (next) next();
    return this;
};


// animator generated by options
// x and y are set on an event